import { ImageSourcePropType } from "react-native";
import { ReactVideoSource } from "react-native-video";

export const homeBanner:ImageSourcePropType = require('./homeBanner.png') 
export const pills:ImageSourcePropType = require('./pills.png') 
export const drugs:ImageSourcePropType = require('./drugs.png') 
export const healthCare:ImageSourcePropType = require('./healthcare.png') 
export const mentalHealth:ImageSourcePropType = require('./mentalHealth.png') 
export const abuse:ImageSourcePropType = require('./abuse.png') 
export const assault:ImageSourcePropType = require('./assault.png') 
export const clinic:ImageSourcePropType = require('./clinic.png') 
export const exploitation:ImageSourcePropType = require('./exploitation.png') 
export const lgbtq:ImageSourcePropType = require('./lgbtq.png') 
export const mental:ImageSourcePropType = require('./mental.png') 
export const needs:ImageSourcePropType = require('./needs.png') 
export const sleep:ImageSourcePropType = require('./sleep.png') 
export const local:ImageSourcePropType = require('./local.png') 
export const selfBg:ImageSourcePropType = require('./SelfBg.png') 
export const logo:ImageSourcePropType = require('./logo.png') 
export const heart:ImageSourcePropType = require('./heart.png') 
export const headset:ImageSourcePropType = require('./headset.png') 
export const phone:ImageSourcePropType = require('./phone.png') 
export const dp:ImageSourcePropType = require('./dp.png') 
export const location:ImageSourcePropType = require('./location.png') 
export const video:any = require('./video.mp4') 